name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master

      # Agregar paso para ejecutar Snyk y generar informe SARIF
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          run: snyk test
          args: --sarif-file-output=snyk.sarif --all-projects

      # Subir resultados de Snyk a GitHub Code Scanning
      - name: Upload Snyk result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

      # Verificar si hay errores y crear ZIP
      - name: Crear ZIP si no hay vulnerabilidades
        if: success() && steps.security.outputs.result == 'success'
        uses: ihiroky/archive-action@v1
        with:
          root_dir: github/security-threats
          file_path: CodigoSeguro.zip

