name: Scan code with Snyk
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        #aqui le pongo un false para que no siga en caso de tener fallos
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk.sarif --all-projects
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif
#########
      
      - name: Snyk localiza todas las vulnerabilidades y si no hay hace zip
        uses: snyk/actions/node@master
        continue-on-error: false # To make sure that SARIF upload gets called
        #aqui le pongo un false para que no siga en caso de tener fallos
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
 
      - name: Crear zip
        uses: ihiroky/archive-action@v1
        with:
          root_dir: github/codeql-action
          file_path: output.zip


          
